### ISSUE TITLE
可以修复一下点点券吗

### ISSUE THREAD

**Issue by gthanmon** [Aaron-lv/sync#10]
好多库已经更新了点点券，大佬可以也修复一下吗

**Comment by Aaron-lv** [comment]
已修

**Comment by gthanmon** [comment]
这速度爱了爱了

**Comment by gthanmon** [comment]
我跑了一遍有个号提示
点击“券后9.9”任务ID已变更
请联系作者等待更新

**Comment by 9k001** [comment]
❗️点点券, 错误!
TypeError: Cannot read property 'todayCurrentSceneSignStatus' of undefined
    at sign (/scripts/jd_necklace.js:151:18)
    at jd_necklace (/scripts/jd_necklace.js:86:11)
    at async /scripts/jd_necklace.js:67:7

同时，普遍火爆。

**Comment by Aaron-lv** [comment]
以上问题已解决
