### ISSUE TITLE
牛牛的浏览任务还是没有完成

### ISSUE THREAD

**Issue by Lockey-J** [Aaron-lv/sync#13]
牛牛的浏览任务还是没有完成

**Comment by Aaron-lv** [comment]
![image](https://user-images.githubusercontent.com/58249729/126897475-e022763c-424c-4f14-979b-2e930ea0f0b3.png)
已测试多次，可以完成

**Comment by Lockey-J** [comment]
可以了。前面运行几次都没有。刚刚重新跑就可以了
