### ISSUE TITLE
求更新:health&beauty

### ISSUE THREAD

**Issue by GaviTate** [Aaron-lv/sync#17]
大佬：
健康社区的关注任务和兑换任务貌似失效，求修

美丽研究院运行到593行function getToken()，会走到err那里，提示"API请求失败……请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)"。更换若干UA都不行，求修

拜谢

**Comment by Aaron-lv** [comment]
健康社区已修复，研究院黑号了= = 暂时修不了

**Comment by Aaron-lv** [comment]
国外ip无法运行美丽研究院，取消所有设置UA变量

**Comment by GaviTate** [comment]
> 
> 
> 健康社区已修复，研究院黑号了= = 暂时修不了

APP里手动可以做，应该没黑？或者半黑？

**Comment by GaviTate** [comment]
> 
> 
> 国外ip无法运行美丽研究院，取消所有设置UA变量

谢谢
IP是TX云的国内IP。我取消变量再看看，不行就放弃了
