### ISSUE TITLE
更新之后 运行宠汪汪系列脚本报错怎么解决

### ISSUE THREAD

**Issue by He219** [Aaron-lv/sync#2]
(node:25784) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '<'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Aaron-lv** [comment]
似乎是青龙的BUG，等青龙作者修复吧。。

**Comment by He219** [comment]
我使用的是v4bot docker

**Comment by Aaron-lv** [comment]
青龙和v4似乎都有这个问题，我是docker1 测试🈚️问题

**Comment by He219** [comment]
有什么办法解决吗😂
