### ISSUE TITLE
大佬，mohe，无限循环了。。

### ISSUE THREAD

**Issue by miwensheng** [Aaron-lv/sync#22]

**Comment by miwensheng** [comment]
![image](https://user-images.githubusercontent.com/32407549/128697760-8edd90fc-c4ac-4f68-a1ae-520a6d0e3ef7.png)

**Comment by Aaron-lv** [comment]
已解决，不是无限循环，是循环做任务，延迟太低，任务完不成才一直循环。

**Comment by miwensheng** [comment]
感谢大佬，已经正常了。
