### ISSUE TITLE
京喜牧场能够默认增加JX_USER_AGENT?

### ISSUE THREAD

**Issue by EchoChan314** [Aaron-lv/sync#28]
看别人代码在这个函数的地方。
function getGetRequest(url) {
  let ua = ``;
  if(JXUserAgent){
    ua = JXUserAgent;
  }else{
    ua = `jdpingou;iPhone;4.9.4;14.6;${randomWord(false,40,40)};network/wifi;model/iPhone9,2;appBuild/100579;ADID/00000000-0000-0000-0000-000000000000;supportApplePay/1;hasUPPay/0;pushNoticeIsOpen/1;hasOCPay/0;supportBestPay/0;session/936;pap/JA2019_3111800;brand/apple;supportJDSHWK/1;Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E200`;
  }
  const method = `GET`;
  let headers = {
    'Origin': `https://st.jingxi.com`,
    'Cookie': $.cookie,
    'Connection': `keep-alive`,
    'Accept': `application/json`,
    'Referer': `https://st.jingxi.com/pingou/jxmc/index.html`,
    'Host': `m.jingxi.com`,
    'User-Agent':ua,
    //'User-Agent':$.isNode() ? (process.env.JD_USER_AGENT ? process.env.JD_USER_AGENT : (require('./USER_AGENTS').USER_AGENT)) : ($.getdata('JDUA') ? $.getdata('JDUA') : "jdapp;iPhone;9.4.4;14.3;network/4g;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1"),
    'Accept-Encoding': `gzip, deflate, br`,
    'Accept-Language': `zh-cn`
  };
  return {url: url, method: method, headers: headers};
}

**Comment by Aaron-lv** [comment]
本来就是随机UA，没UA能跑？......

**Comment by EchoChan314** [comment]
因为邀请助力的那个没有完成，但加了默认UA那个邀请助力可以完成了。

**Comment by Aaron-lv** [comment]
不是UA问题，是token没有给助力循环加，等下修

**Comment by EchoChan314** [comment]
多谢。
