### ISSUE TITLE
宠汪汪兑换，等待时间延迟比较大

### ISSUE THREAD

**Issue by mjyhj** [Aaron-lv/sync#4]
JDJR验证用时: 14.793s
脚本开始请求时间 2021-07-15 15:59:16 | 272
等待时间 43
脚本开始兑换500京豆时间 2021-07-15 16:00:01 | 681

JDJR验证用时: 3.519s
脚本开始请求时间 2021-07-15 15:59:05 | 364
等待时间 54
脚本开始兑换500京豆时间 2021-07-15 16:00:01 | 635

普遍误差的时间，最后基本都是1秒后开始，最大的时候是4秒才开始。
这个能否等待到55秒左右，重新检测一下时间当前时间，再等待倒计时开始抢，降低延迟

**Comment by Aaron-lv** [comment]
这个应该是账号太多并发导致的延迟，现在是延迟到59秒，我稍后把延迟时间改成变量吧  自己测试多少合适

**Comment by mjyhj** [comment]
> 这个应该是账号太多并发导致的延迟，现在是延迟到59秒，我稍后把延迟时间改成变量吧 自己测试多少合适

NICE

**Comment by Aaron-lv** [comment]
已更新，变量  JOY_STARTTIME

**Comment by mjyhj** [comment]
> 已更新，变量 JOY_STARTTIME

OK，我今晚测试下

**Comment by mjyhj** [comment]
> 已更新，变量 JOY_STARTTIME

可以了，我设置了等待到58秒，不过今晚延迟更大了。变成2秒才开始兑换。
感觉还是要倒数到55秒，再执行一次获取时间，再开始倒数，降低延迟比较好

**Comment by Aaron-lv** [comment]
计算延迟没有问题很准时，是你号太多，导致进程卡延迟了

**Comment by Aaron-lv** [comment]
Jul 16 23:59:01 JDJR验证中......
Jul 16 23:59:03 验证失败: 1
Jul 16 23:59:04 验证失败: 1
Jul 16 23:59:06 JDJR验证用时: 5.537s
Jul 16 23:59:06 脚本开始请求时间 2021-07-16 23:59:06 | 664
Jul 16 23:59:06 等待时间 53
Jul 16 23:59:07 JDJR验证用时: 6.12s
Jul 16 23:59:07 脚本开始请求时间 2021-07-16 23:59:07 | 296
Jul 16 23:59:07 等待时间 52
Jul 16 23:59:59 
Jul 16 23:59:59 debug场次:beanConfigs16
Jul 16 23:59:59 
Jul 16 23:59:59 20京豆当前库存:0，id：342
Jul 16 23:59:59 500京豆当前库存:0，id：343
Jul 16 23:59:59 
Jul 16 23:59:59 按您设置的兑换500京豆失败，原因：京豆库存不足，已抢完，请下一场再兑换
