### ISSUE TITLE
京喜88红包无法读取80个以前的ck

### ISSUE THREAD

**Issue by fengshaoyule** [Aaron-lv/sync#46]
京喜88红包 只能读取80个ck 多了也无法读取，只会显示80个ck

**Comment by fengshaoyule** [comment]
已经删除容器 重新安装了一次 还是只读取80个 超过了不读取

**Comment by Aaron-lv** [comment]
@fengshaoyule

**Comment by Aaron-lv** [comment]
![61AA04C4-7FF3-4D9E-9801-FA3DF7B6A952](https://user-images.githubusercontent.com/58249729/137245089-d9f8aace-55c6-4361-870d-65a617b1e1c1.jpeg)
自行查找问题 非脚本问题

**Comment by Aaron-lv** [comment]
@yksuhx118 你可以试试一个ck复制一百次，就有100个ck了

**Comment by fengshaoyule** [comment]
已经搞定了 换个别人的脚本 没问题了

**Comment by FangDoudouY** [comment]
@Aaron-lv 喂喂喂~
