### ISSUE TITLE
jd_cfd_mooncake.js合成月饼失效了 都是合成0 没奖励了

### ISSUE THREAD

**Issue by qqeip** [Aaron-lv/sync#49]
jd_cfd_mooncake.js合成月饼失效了 都是合成0 没奖励了
合成月饼成功：获得0元红包

合成月饼没有奖励，停止运行

合成月饼:0

**Comment by Aaron-lv** [comment]
建议问问东哥为啥不给红包了

**Comment by hyzaw** [comment]
@Aaron-lv ？
