### ISSUE TITLE
jd_redPacket.js 出错

### ISSUE THREAD

**Issue by jim114042** [Aaron-lv/sync#60]
开始领取【逛活动】任务所得红包奖励

❗️京东全民开红包, 错误!
TypeError: Cannot read properties of undefined (reading 'success')
    at /home/myid/jd/scripts/jd_redPacket.js:392:25
    at got.post.then.message (/home/myid/jd/scripts/jd_redPacket.js:700:5772)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Aaron-lv** [comment]
已添加log验证，修不动

**Comment by lsh26** [comment]
> 已添加log验证，修不动

我不信，快修

**Comment by FangDoudouY** [comment]
@hyzaw @Hbklink说修个鸡巴

**Comment by hyzaw** [comment]
@FangDoudouY 修你鸡巴

**Comment by FangDoudouY** [comment]
@hyzaw 修你鸡巴

**Comment by hyzaw** [comment]
@FangDoudouY 修你鸡巴

**Comment by hyzaw** [comment]
@hyzaw 小小邮箱要炸了
