### ISSUE TITLE
财富岛新的任务

### ISSUE THREAD

**Issue by EchoChan314** [Aaron-lv/sync#63]
不知道是不是灰度测试
![eed07ed1b6f17e6e2bd11369a1e521b](https://user-images.githubusercontent.com/5077551/140650746-f14e0687-a14c-4116-ba4e-c1debc680c30.jpg)
合成大生鲜（跟合成珍珠小游戏一样）和签到领钱（不过获得的是京豆，不是红包）

**Comment by thy486** [comment]
会做。拿跑脚本的号再问

**Comment by Aaron-lv** [comment]
一直没有这个任务，写不了

**Comment by EchoChan314** [comment]
> 一直没有这个任务，写不了

估计是灰度测试

https://st.jingxi.com/sns/202106/29/signinhb_new/index.html?nativeConfig=%7B%22immersion%22%3A%221%22%2C%22toColor%22%3A%20%22%23ff413e%22%2C%22showTitle%22%3A%220%22%2C%22titleImg%22%3A%22https%3A%2F%2Fimg14.360buyimg.com%2Fimg%2Fs310x60_jfs%2Ft1%2F182288%2F39%2F11805%2F6453%2F60db126dE4bfbe1e4%2Fbdde1ac9b3aba5c6.png%22%2C%22titleImgSize%22%3A%20%22162x26%22%7D&smp=b6093950d9c29f4df2bc47d4e92452e3&signhb_source=5&share_qywx=3,ddee7065070cffe475222aff3973f1a5&ispp=1&tk=&jxsid=16363511335519698748&PTAG=17053.57.1&_fromplatform=jxapp&utm_source=iosapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL&ad_od=share 这是签到领钱链接。
另一个：
14:/#ZAntF57XfvXLxw%，财富岛全新合成赛季
合成生鲜赢喜豆
天天抽超级壕礼
