### ISSUE TITLE
合成财富岛月饼 感觉还不如上一个版 现在每个都是固定100次 以前是15次 20次就合成成功了

### ISSUE THREAD

**Issue by qqeip** [Aaron-lv/sync#71]
合成财富岛月饼 感觉还不如上一个版 现在每个都是固定100次 以前是15次 20次就合成成功了
现在100次 有时还不成功
https://raw.githubusercontent.com/Mrl-xq/jd/master/jd_cfd_mooncake.js

**Comment by likeu99** [comment]
@qqeip 月饼都没了，合成个der（

**Comment by qqeip** [comment]
每次一毛钱啊 每天可以提1块红包 不过现红包也要抢了
