### ISSUE TITLE
jd_bean_home.js 账号异常不会自动跳出，无限循环错误

### ISSUE THREAD

**Issue by LingFeng0918** [Aaron-lv/sync#8]
![image](https://user-images.githubusercontent.com/39041664/126662315-1f3aa787-cf9b-464c-94e1-a8cadb8c1bac.png)

**Comment by Aaron-lv** [comment]
这个不是我新添加的活动报错，是之前的活动   检测cookie格式是否错误

**Comment by Aaron-lv** [comment]
会搬运不会修？？？  建议去掉我互助码的都自己修
