### ISSUE TITLE
更新依赖后脚本报错

### ISSUE THREAD

**Issue by gthanmon** [Aaron-lv/sync#80]
(node:223064) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /jd/scripts/node_modules/got/dist/source/index.js
require() of ES modules is not supported.
require() of /jd/scripts/node_modules/got/dist/source/index.js from /jd/scripts/jd_sendBeans.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /jd/scripts/node_modules/got/package.json.

**Comment by Aaron-lv** [comment]
回退了

**Comment by gthanmon** [comment]
才发现 好的
