### ISSUE TITLE
无法更新scripts

### ISSUE THREAD

**Issue by showphi** [Aaron-lv/sync#88]
多了个https://ghproxy.com/，导致无法访问仓库，重装问题依然

[*] 开始更新仓库：/jd/scripts
Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/Aaron-lv/sync.git/': The requested URL returned error: 403
error: Could not fetch origin
fatal: unable to access 'https://ghproxy.com/https://github.com/Aaron-lv/sync.git/': The requested URL returned error: 403
HEAD is now at a545a78b 更新
[ERROR] Scripts 仓库更新失败，请检查原因...

**Comment by shufflewzc** [comment]
@showphi 把gh去掉

**Comment by showphi** [comment]
> @showphi 把gh去掉

请问在哪里去？找了很久，没找到

**Comment by SuperManito** [comment]
> > @showphi 把gh去掉
> 
> 请问在哪里去掉？找了很久，没找到

### 官方通知内容 [点此查看](https://supermanito.github.io/Helloworld/#/start/%E9%87%8D%E8%A6%81%E9%80%9A%E7%9F%A5?id=_2022-01-19)

- 一键解决命令：
```bash
docker exec -it jd bash -c "cd /jd/scripts && git remote set-url origin https://github.com/Aaron-lv/sync.git"
```

![image](https://user-images.githubusercontent.com/68613938/150129712-8ce4ba39-2575-4213-adcd-d82432e67b5a.png)
